### ISSUE TITLE
关于This的修正

### ISSUE THREAD

**Issue by zhangzhengyi12** [markyun/My-blog#130]
在事件中，this指向触发这个事件的对象，特殊的是，IE中的attachEvent中的this总是指向全局对象Window；

应修改成 在事件中，this指向事件监听者

**Comment by hanyufeiyan** [comment]
谢谢您的来信~我会尽快回复您~

**Comment by liangshuangs** [comment]
你发给我的邮件已经收到。

**Comment by andersonyp** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
