### ISSUE TITLE
水平垂直居中二 使用relative，不会水平垂直居中

### ISSUE THREAD

**Issue by DaiZhaoedu** [markyun/My-blog#134]
![image](https://user-images.githubusercontent.com/45584852/61883696-7f8f5600-af2d-11e9-89cb-81ab84dc4afa.png)

**Comment by GanYihuan** [comment]
[1](https://i.loli.net/2019/07/26/5d3a648be3fc350042.png)

**Comment by GanYihuan** [comment]
![连接](https://i.loli.net/2019/07/26/5d3a64d12166139211.png)

**Comment by GanYihuan** [comment]
![连接](https://i.loli.net/2019/07/26/5d3a648be3fc350042.png)

**Comment by DaiZhaoedu** [comment]
谢谢我知道我的问题说在了
