### ISSUE TITLE
转正答辩（初稿）

### ISSUE THREAD

**Issue by markyun** [markyun/My-blog#23]
##PS： 明天提前转正了，临时通知要做一个答辩。立马写啊，囧！
——————

大家好，首先很感谢大家能够抽出宝贵的时间来参加我的答辩， 时间过的很很快，转眼3个月过去了，先简单自我介绍： 

打开PPT第二页。

我是2014年4月正式加入ZTE的UED团队。 

打开PPT第3页 介绍 岗位情况，职责。

我们团队一共11个人，其中女性占7个，在软件行业其实很少见啊。有没有。
 
个个都有自己的特长，所以工作起来很愉快。

另外我觉得我们办公室是所有办公室看起来最整洁的。 

我个人目前对我们团队能力认识是这样的： 

就是能让产品从 80分进化到90分甚至 100 分，甚至更好，当然这个进化并不仅仅是指页面更好看了，而是整个产品体验的进化。

（
原来用户想修改个人资料，原来虽然也能用，但不好用总觉得有些操作反人类。 而我们团队接到任务，会从头到尾进行，需求分析（用户角度出发，想想流程），交互设计，UI设计，页面设计，最后由前端来实现前面所以的成果加细节，给用户【大气美观】，特好用的修改头像功能。
）
 
##我现在的工作：

         参与项目，快速高质量完成实现效果图，精确到1px；
       
         与团队成员，UI设计，产品经理的沟通；
       
         做好的页面结构，页面重构和用户体验；
       
         处理hack，兼容、写出优美的代码格式；
       
         不断优化产品、沉淀经验，拥抱最新前端技术。

我短期主要深入学习的是JS、排第2的是HTML5、CSS3。接下来是web APP。

当然这只是主要学习点，其他一些比较知名的也会有去了解，知道怎么用，有什么作用。 

对前端圈子关注比较多，通过长期的学习和观察，我觉得：评价那个技术好是没实际作用的，

正如：

## 没有最强的武功，只有最强的武者。

针对项目，在做技术选型的时候，只有对一项技术或者新技术充分了解，知道该技术的适用场景，与其他技术对比，存在的优势和不足，这样才能让整个系统没有严重的瓶颈。

就比如前一阵刚刚出来的SWIFT 和原来的Objective-C进行对比，有人就说，【这下大家都要从头开始，零起步了】
其实这个认知是错误的，以为学会了SWIFT或者Objective-C 就能开发IOS的APP，因为SWIFT或Objective-C 只是一门单纯的语言，而做IOS APP开发，需要全面的掌握编程思想，框架，与后端数据层的配合，想把APP做的“漂亮”，更是需要学习 交互、UI、界面设计规范、甚至还需要学习美学、为动效设计算法，让你的效果具有物体运动的物理感，这样你做出来的APP灵活自然，有大师的味道，而不会显得很生硬。

这个期间，你肯定会遇到很多问题和错误，然后发现书上、网络上都找不到现成的解决办法，以前没有类似的案例可以模仿，这个时候，就是才真正体现出你的价值，发挥自己的潜力，做别人不一定能解决的事情，解决掉。 

对于前端开发这个行业，我还是比较看好的 ............【想理由】

## 我的爱好

可能比较小众，就连我辅修的【行为心理学Behavioral Psychology】都不是心理学领域主流的。

因为其他专家认为通过普遍的行为标准来推断一个有着特定行为习惯的人是不太科学的。外在的环境、文化也会对人的行为有很大的影响，导致判断者的判断结果过于肤浅。

   其实我觉得专家的说法不完全对啦。

 不狂爱足球，篮球，更喜欢射击、赛车类的、放假了喜欢到处走走看看，我的电脑上，累计的照片超过了10万张。

接下来： PPT 4到14页， 我做了这些事情。

## 公司的不足之处： ##

1、 有些流程比较乱，比如说改就改。 

2、 有些需求拖时间太久了，  

3、薪资在同行业来看稍微缺乏竞争力。

## 我需要提升的： ##

年纪轻，很多东西还需要深入的学习吧。把自己视野放到国内外，同时提高自己的英语水平。有机会出版一本自己的技术书。
 

工作方面，时间管理 养成的几个习惯：
 
1、工作邮件每天必须全部看完，就算是与我无关的公司的邮件，也要设为已读。

2、上班第一件事，先把难度最大的问题先处理掉。然后处理其他相对简单的任务。

3、任何任务会在要求的工作时间 之前完成，留1天或者0.5天防止不能及时提交输出物。

4、任何待办List都有一个优先级，谁的优先级高做谁。需要自己判断优先级。

5、在时间允许的前提下，把事情完成的最优化。

6、Read later,看见有用的资料，上班没有时间看先保存在Pocke应用。

7、不断学习新技术，新知识，技多不压身，深度为主，广度为辅，让自己竞争力更强。

2014-7-16 23:33:55

**Comment by xiaolei0808** [comment]
最近也要转正答辩了，借鉴一下，打开点思路 :)

**Comment by lujing2** [comment]
这是转正答辩的内容？
