### ISSUE TITLE
如何一辈子耐得住寂寞、不浮躁，如何修炼？

### ISSUE THREAD

**Issue by markyun** [markyun/My-blog#3]
在知乎上看见有人问了这个问题http://www.zhihu.com/question/21009054
对于年轻的我和很多人一样，所以认真看了一下。觉得这句说的挺对：
“
有句话叫耐得住寂寞，才能守得住繁华。只有在耐得住一时的寂寞，吃的了苦，下得了功夫才能得到成绩，然后就才能在人前显贵，风光。” 

很多人看了一些励志的青春的让人激动的电影。然后就说自己要怎么怎么样。改变自己。我觉得都是故事编的好。现实哪有这么完美，只要做好现在的自己。活在当下，不要浪费生命就好。

**Comment by whps** [comment]
帕尔哈提说过：`人生除了死就是玩。`
当然这个玩不是玩物丧志，没必要憋屈自己，快乐才是主题！
