### ISSUE TITLE
面试题中javascript部分中有个小错误

### ISSUE THREAD

**Issue by kisnows** [markyun/My-blog#32]
[这里](https://github.com/markyun/My-blog/tree/master/Front-end-Developer-Questions/Questions-and-Answers)
其中
  >写一个通用的事件侦听器函数中：

`element.removeEnentListener(type, handler, false);`中的`removeEnentListener`是不是拼写有错误。
应该是`removeEventListener`吧。

**Comment by markyun** [comment]
好的谢谢指正。
