### ISSUE TITLE
ZTEsoft-UED团队 招前端工程师

### ISSUE THREAD

**Issue by markyun** [markyun/My-blog#35]
中兴软创 UED团队 招 前端开发工程师（2名） 

工作地点： 南京

工作时间： 早九晚五 （几乎不加班）

工作职责：
   与设计MM及后端开发协作完成项目的前端开发与交互效果;

职位要求：
1、2年以上 Web 前端工作经验，熟练掌握 HTML/CSS/JavaScript基础知识；
2、具备良好的代码风格和编程习惯，能够使用模块化的方式编写代码；
3、具备较好的问题分析与解决能力，能够进行跨部门协作开发；
4、有复杂网站/HTML5/CSS3/Web系统应用开发经验更好；
5、具有良好的审美观和用户体验意识及熟悉UED工作流程的当然更好；

工作福利：
1、五险一金+补充商业保险
2、年终绩效考核奖
4、带薪年假、节假日福利 、节日礼物、生日礼物
5、定期团队活动经费、公司组织春游活动、家属亲子活动。

我们有专业的分工：需求分析、原型设计、视觉设计、前端开发、后端开发、测试团队、运维团队；绝对不会让你一人从头干到尾。

其他还有一些杂七杂八的福利，比如团队的妹纸数量多于汉子，买（技术书）部门全报销，公司班车覆盖南京主城区，接送到小区门口或地铁站，自己有什么好想法提出来领导就会帮你实现。

我们是一个年轻的团队，欢迎想来南京发展的朋友找我聊聊。

**Comment by lpgray** [comment]
病句：我们团队几乎从不加班

**Comment by markyun** [comment]
@lpgray  已修正。

**Comment by zhuziyi1989** [comment]
可惜在南京~

**Comment by andybruse** [comment]
中兴软创？

在 2015-05-19 19:13:17，"马云云_理想青年" <notifications@github.com> 写道：


@lpgray 已修正。

**Comment by markyun** [comment]
@andybruse  yeah,中兴软创科技股份有限公司

**Comment by andybruse** [comment]
No

**Comment by markyun** [comment]
@andybruse   are you ok？

**Comment by JasonFang93** [comment]
是否招应届毕业生呢？

**Comment by markyun** [comment]
招啊，可以把你简历发给我。 不过应届生最好走校招途径，要求会简单一点。

**Comment by markyun** [comment]
@JasonFang93 招啊，可以把你简历发给我。 不过应届生最好走校招途径，要求会简单一点。

**Comment by mumunana** [comment]
赞。

**Comment by JasonFang93** [comment]
@markyun 谢谢建议，已经看到学校就业网上中兴软创的校招信息了，不过，只看到招软件研发工程师，前端也是包括在这里面吗？

**Comment by markyun** [comment]
@JasonFang93  包括的，到时候会问你一些问题，你多往这方面提就会问你的发展意向。

**Comment by ehazon** [comment]
夸部门 = 跨部门

**Comment by Jason-mor** [comment]
中兴软创的待遇如何？？？是否还有招人计划？？？
