### ISSUE TITLE
知识碎片

### ISSUE THREAD

**Issue by markyun** [markyun/My-blog#36]
（个人整理，各种碎片知识，鸡汤段子），不定期更新。   

用户对待产品的态度，和对待人的区别不大，所以，产品的交互设计，应该更为礼貌。不应打断正常的操作流，不应强调交互（当用户意识到了强调的交互，那说明喧宾夺主了）而是“透明”地去实现用户的目标。为此，可以设计良好反馈、非模态信息、识别常用和例外、提供选择而不是提问等等，我们希望面对的是更聪明、简约的“人工智能”。最后，不论你的界面多酷，越少越好。

用户的阅读习惯一般是：首先浏览屏幕最上方，从左到右；然后浏览左边从上到下，寻找关键字；接着，找到关键字之后再从左到右的阅读。这样的阅读习惯被称之为F-Pattern，也是设计师设计网页的原则，内容依据重要性不同安排在不同的位置。

短信，邮件，以及push notification这三种通知用户的手段的不同之处在于实效性。90%的短信在3分钟内被读到，适合紧急通知，但不要期望用户会回过头来“复习”以前的内容；邮件发出去后平均要6.4小时才能被收件人看到，适合用户可能会回头看的东西，比如收款凭证，账号修改信息等；push notificatiojn与短信类似，但比短信友好点（免费，不像短信那么intrusive，所以也不太像短信那么容易让人及时查看）。 

  指向性动效能够让用户清晰的感受到物体与物体的位置关系，以及信息的层级架构。

  开发的基本操作流程

```
(1)明确目标；
(2)如何收集想法并划分优先级；
(3)跨团队之间的协作；
(4)公司的透明文化，让他人知道你在干什么；
(5)产品设计；
(6)指明第一负责人；
(7)迭代开发；
(8)同步&报告状态；
(9)发布产品&持续监控。
```

  什么是“更好”的Demo：

```
核心功能完整，主要任务流足够深度
交互保真程度高，操作的体验感真实
根据场合与目的有适当的视觉细节
避免制作过程“过于费工”或“效率低下”
```

  移动设计要素

```
清晰的视觉纵线、信息的分组、极致的减法、利用选择代替输入、标签及文字的排布方式、
依靠明文确认密码、合理的键盘利用、校验的小秘密之外，还有很多很多秘籍没有写，
比如清晰的步骤、用户的语音、移动端特殊的情景、合理的说明、及时的反馈、锚点置顶、
主动做与次动作的位置、给与建议、给予限制、适当的帮助、标签页设计、颜色的信息传达、循序渐进的表单
```

  如果你的投资回报能超过6.55%，购房贷款建议采用20年，否则采用10年还款。如果你贷款数额不高，年限要求也不高，那就一定要用等额本金的方法贷款。

  看房的关注点大致包括：小区基本信息、采光、通风、视野、动线、功能分区、得房、赠送、装修、设备、水电气暖等等。里面还可以细分，比如采光可以分为采光面数、采光面积比、采光情况、是否明厨明卫、总面宽、客厅面宽、主卧面宽等等。

  在职场里，收到指令要回复，遇到困难要沟通，项目进展要按节点通报，安排要落实。这不是繁文缛节，这是一个公司的基本规范。要尽心尽力，说到做到，有始有终，积极主动，你才能成长，公司也才能成长。不要玻璃心，也不要有惰性，更不要骄横，有多少人，有才华，有远志，不约束自己

  苦难并不值得的追求，但它确实能磨练你的意志，它使你的多巴胺水平降低促进你更多的思考，让你认清自己。 它不会一定能带来成功，苦难在成功之前没有任何价值。

  MVC设计模式是一个很好创建软件的途径，它所提倡的一些原则，像内容和显示互相分离可能比较好理解。但是如果你要隔离模型、视图和控制器的构件，你可能需要重新思考你的应用程序，尤其是应用程序的构架方面。如果你肯接受MVC，并且有能力应付它所带来的额外的工作和复杂性，MVC将会使你的软件在健壮性，代码重用和结构方面上一个新的台阶

  IE9及其以下版本的浏览器限制每个样式表最多有4096个选择器，也限制了31个复合的样式表和每个页面包含的<style></style>元素。所有超过这个限制的内容都会被浏览器忽略。
  是把你的CSS样式表分开还是重构? 建议后者。

   HTML5包含:

```
语义：能够让你更恰当地描述你的内容是什么。
连通性：能够让你和服务器之间通过创新的新技术方法进行通信。
离线 & 存储：能够让网页在客户端本地存储数据以及更高效地离线运行。
多媒体：使 video 和 audio 成为了在所有 Web 中的一等公民。
2D/3D 绘图 & 效果：提供了一个更加分化范围的呈现选择。
性能 & 集成：提供了非常显著的性能优化和更有效的计算机硬件使用。
设备访问 Device Access：能够处理各种输入和输出设备。
样式设计: 让作者们来创作更加复杂的主题！
```

  前端现在可深入的领域真心多：前后端分离、前端工程化、前端质量体系、前端工具与生态圈、数据可视化、下一代类库框架、前端服务化、前端安全、设计工业化…… 好多领域都值得研究一辈子 @玉伯也叫射雕

  优秀的前端工程师应该具备快速学习能力。推动Web发展的技术并不是静止不动的，这些技术几乎每天都在变化，如果没有快速学习能力，你就跟不上Web发展的步伐。你必须不断提升自己，不断学习新技术、新模式；仅仅依靠今天的知识无法适应未来。Web的明天与今天必将有天壤之别，而你的工作就是要搞清楚如何通过自己的Web应用程序来体现这种翻天覆地的变化。

  流程本身就是一把双刃剑，有利有弊。一方面，它使我们的需求变得有序，使前端能够在处理一个需求时，不会频繁被其他插队的需求打断。并且因为发布有时间点的设定，所以测试工作会更加严谨，这有助于提升代码的质量。因此对于我们来讲，流程带来的好处是显而易见的；但另一方面，它额外地增加了做事的成本，涉及ASSETS发布的需求，就像赶某班火车一样，错过了就只能等下一班，所以也给需求方带来了许多不便，有待改进，不过这可以通过长期的合作而慢慢被弱化，双方达成了一种默契以后，情况会好很多。

  前端由无到有。 前端架构概念的建立，包括与设计、后台、产品的配合，改变他们原有的、已习惯的开发流程确实是个不小的挑战。
  用户体验设计应该贯穿于产品从萌芽到出生的整个过程，产品原型、视觉设计、前端开发、后端开发甚至还包括产品测试大家都应该有份。只有各个环节的同学都把这个事儿当事儿了，那么做出来的产品才有可能是好产品。

  关于毕业生找工作

```
小公司看老板--老板靠谱，愿意分享，空间无限 
中公司看制度--制度合理，空间可见，成长阶段 
大公司看文化--文化适合，空间有限，平台价值
```

  大小公司实习的优点：

```
大公司：可以观察、学习企业文化、运营流程；可能有比较多的培训项目；往往会指派一个mentor来帮助你；有很多其他的实习生可以成为朋友。
小公司：公司以执行为目标，可以担当多种职务，较完整地理解如何解决一个问题。小公司步伐较快，没有太细的职能划分，有更多的自由度，比较少官僚会议等。
```

  只有当你自己拥有并能够提供别人所需的【有效利用价值】，别人才乐意向你提供他的【有效利用价值】。这就是人脉的基础。

  椅背不能靠,一靠成山炮.
  食物送到嘴,跪舔打断腿.
  喝汤是例外,低头不奇怪.

  最傻的事情莫过于向别人证明自己过的有多好。但凡需要被证明的,都是你避而不及的弱点。比如内心强大,比如活得潇洒。

  论功劳，一般情况下，开发完成前，产品，美术，技术，测试，项管加起来占一半功劳，开发完成后，运营推广占了另一半功劳。

  IE 10 的条件注释.

```
方法：用 JavaScript 把 useragent 添加到 html 这个元素里
var doc = document.documentElement;
doc.setAttribute('data-useragent', navigator.userAgent);
IE 10 浏览器的用户代理字符串：
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)
结果：
<html data-useragent="Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)">
接下来，我们只需要很简单的 CSS 样色：
html[data-useragent*='MSIE 10.0'] h1 {
  color: blue;
}
```

  DIV颜色块高亮

```
[].forEach.call($$("*"),function(a){
  a.style.outline="1px solid #"+(~~(Math.random()*(1<<24))).toString(16)
})
```

  需要了解到该股以下情况：

```
1、所在行业的发展前景；
2、公司在行业内的发展前景，或垄断地位；
3、未来3－5年的快速增长势头，且前景明确；
4、财务稳健，没有疑问点；
5、分红扩股正常；
6、资产负债比合理；
7、现金流量正常；
8、信息披露充分；
9、价格有吸引力；
```

**Comment by keibe** [comment]
博主，能不能认识一下，很膜拜你，我qq微信：276380177

**Comment by Thinking80s** [comment]
mark

**Comment by ericmoshare** [comment]
Love that!
看似琐碎，絮絮叨叨
然则细看非常有意思
