### ISSUE TITLE
javascript基本数据类型错了吧？

### ISSUE THREAD

**Issue by kmCha** [markyun/My-blog#45]
`number,string,boolean,object,undefined`应该是
`number,string,boolean,null,undefined`吧？

**Comment by SimplyY** [comment]
+1..

**Comment by wagnlinzh** [comment]
@kmCha null 是对象类型的,
```
typeof null //object
```

关于null和undefined的历史渊源 可以看一下这篇文章:

http://www.ruanyifeng.com/blog/2014/03/undefined-vs-null.html

: )

**Comment by kmCha** [comment]
@wagnlinzh null是对象类型算是一个bug吧，他会被typeof解析为object是因为底层对null的二进制表示全为0，而typeof判定为object的条件是低三位为0，他自然就会被解析成object了，对于基本数据类型的官方说明：
http://www.ecma-international.org/ecma-262/5.1/#sec-4.3.2
https://developer.mozilla.org/en-US/docs/Glossary/Primitive

**Comment by wagnlinzh** [comment]
@kmCha 不好意思我纠正一下, 翻了一下书,的确是我弄混淆了, Null 是基本类型的. (^_^)


完整的说, JS中的数据类型分两类: 简单类型(也就是基本类型)和复杂类型

- 简单类型(基本类型)5种: Undefined, Null, Boolean, Number, String
- 复杂类型: Object.
