### ISSUE TITLE
模块化开发

### ISSUE THREAD

**Issue by wangyijunjunjun** [markyun/My-blog#57]
原文:

模块化开发怎么做？

立即执行函数,不暴露私有成员

    var module1 = (function(){
    　　　　var _count = 0;
    　　　　var m1 = function(){
    　　　　　　//...
    　　　　};
    　　　　var m2 = function(){
    　　　　　　//...
    　　　　};
    　　　　return {
    　　　　　　m1 : m1,
    　　　　　　m2 : m2
    　　　　};
    　　})();
（待完善）

我晕,这有点水啊....

最后的分号前面的一对括号应该放在右括号里面....

应该是:

}());

希望作者能够切实提高自身水平,以及对待问题更严谨 : )

**Comment by liyunsong** [comment]
😢

**Comment by huanshen** [comment]
这样子也是可以的，高级程序设计里面就有这样的，而且也可以自己写一个简单的验证一下

**Comment by wangyijunjunjun** [comment]
@huanshen OK

**Comment by daiyonger** [comment]
--

**Comment by markyun** [comment]
@wangyijunjunjun  感谢教导
