### ISSUE TITLE
闭包的例子问题、

### ISSUE THREAD

**Issue by SunoAries** [markyun/My-blog#58]
var nodes = document.getElementsByTagName("li");
    for(i = 0;i<nodes.length;i+= 1){
        nodes[i].onclick = function(){
            console.log(i+1);//不用闭包的话，值每次都是4
        }(i);
    }
  
未实现闭包，也未实现功能0.0。做了以下改进：

    var nodes = document.getElementsByTagName("li");
    for(i = 0;i<nodes.length;i+= 1){
        nodes[i].onclick = (function(i){
                  return function() {
                  	 console.log(i);
                  } //不用闭包的话，值每次都是4
                })(i);
    }

**Comment by pandasjw** [comment]
其实这个例子还是立即执行来保存变量的做法。用es6块级作用域就好了。。。

**Comment by SunoAries** [comment]
这个es6块级作用域不是太清楚，我猜是要用let声明一个变量，用遍历时的 i 赋值。再次调用点击事件的时候，就能够正确打印日志？求指点~~ 
for(i = 0;i<nodes.length;i+= 1){
    		let x=i;
        nodes[i].onclick = function(){
        	
        	console.log(x+1);//不用闭包的话，值每次都是4
        };
    }
原本的例子是立即执行之后没有return，所以会是返回undefined。也就是说没有注册点击事件。立即执行就只是log了 i 的遍历。
闭包的作用一部分就是为了模拟块级作用域。但是毕竟面试别人要问，是吧。哈哈哈

**Comment by pandasjw** [comment]
es6中的第一个就是let作用域，它就相当于块级作用域。``` for(let i = 0;  i<node.length;  i++) ```就可以了，[参见阮老师的入门](http://es6.ruanyifeng.com/#docs/let)

**Comment by markyun** [comment]
谢谢提醒，已经修改。
