### ISSUE TITLE
关于JS数据类型的内存图

### ISSUE THREAD

**Issue by lenient** [markyun/My-blog#59]
对原文内存图中变量string画在栈(stack)里的图例存疑。

> 原始数据类型直接存储在栈(stack)中的简单数据段，占据空间小、大小固定，属于被频繁使用数据，所以放入栈中存储；

如果说栈里的数据大小固定，那对于一个很长的string将如何存储呢？

对于下面这段代码，
~~~~
var str1 = "string";
var str2 = "string";
console.log(str1 === str2); // true
~~~~

个人觉得变量string的值应该是存放在堆(heap)中，而栈中保存的是值在堆中的地址。
也就是说，str1和str2分别在栈里分配了空间，这2个空间存储了同一个在堆中"string"的地址。

由于没有找到充分的文档说明，也不确定这种想法是否正确。

**Comment by markyun** [comment]
有清晰和有明确答案的时候，可以再次提交issues
