### ISSUE TITLE
绝对定位的div居中

### ISSUE THREAD

**Issue by qiuyudiwutong** [markyun/My-blog#60]
文中给出的方法亲测无效…

**Comment by StevenYuysy** [comment]
@qiuyudiwutong  是无效的，刚刚测试了一下，这个方法仅仅适用于让 div 百分百的充满整个空间。具体你可以看这个例子： http://stackoverflow.com/questions/28080910/what-does-top-0-left-0-bottom-0-right-0-mean

至于如何让 div 居中，有三种做法：（这里指的是垂直水平居中）

- 已知元素的宽高，通过设置元素的`top: 50%; left: 50%` 以及 `margin` 分别减去自身宽高的一半
- 不知道元素的宽高，通过`top: 50%; left: 50%`  以及 `transform: transformX(-50%);` `transform: transformY(-50%);` 来解决
- 最后一种办法是用 flex 布局，简洁快速，兼容性现在也跟上去了。推荐使用，只要在父容器上面设置 `display: flex; align-items: center; justify-content: center;`就可以了。

但是我不知道作者还是否维护这个 blog（毕竟那么多 issue 没解决，而且也很久没更新了），如果作者还有维护的话，我可以再 PR 更改一下。

你可以移步这里看一下我写的关于元素居中的方法：http://www.jianshu.com/p/a159d22d4b97

**Comment by jinjidecoco** [comment]
亲发错邮件了嘛


来自 魅族 MX5

-------- 原始邮件 --------
发件人：Steven余思烨 <notifications@github.com>
时间：周三 9月7日 22:26
收件人：markyun/My-blog <My-blog@noreply.github.com>
主题：Re: [markyun/My-blog] 绝对定位的div居中 (#60)

**Comment by StevenYuysy** [comment]
@jinjidecoco 
邮件不是我发的，是 github 上面的通知，原因是因为你 watch 了这个 repo。仅此而已。

**Comment by jinjidecoco** [comment]
不好意思，谢了


来自 魅族 MX5

-------- 原始邮件 --------
发件人：Steven余思烨 <notifications@github.com>
时间：周四 9月8日 10:11
收件人：markyun/My-blog <My-blog@noreply.github.com>
抄送：jinjidecoco <18895627215@163.com>,Mention <mention@noreply.github.com>
主题：Re: [markyun/My-blog] 绝对定位的div居中 (#60)

**Comment by StevenYuysy** [comment]
已提交 PR #68 ， 合并以后，问题可以关闭了。

**Comment by liaolongdong** [comment]
水平垂直居中汇总，可以参考：https://github.com/liaolongdong/study-materials/blob/master/css-practice-files/%E7%BD%91%E9%A1%B5%E5%85%83%E7%B4%A0CSS%E6%B0%B4%E5%B9%B3%E5%B1%85%E4%B8%AD%E3%80%81%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD%E3%80%81%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD%E6%B1%87%E6%80%BB.html

**Comment by markyun** [comment]
谢谢，已经修改。
