### ISSUE TITLE
千位分隔符，不要搞得那么麻烦。

### ISSUE THREAD

**Issue by hzz780** [markyun/My-blog#61]
var aa = 123123123;
aa.toLocaleString();
"123,123,123"

**Comment by markyun** [comment]
toLocaleString，是把数组转换为本地字符串，具有不可控性，所以还是自己写算法更放心呢~
		function commafy(num) {
		    return num && num
		        .toString()
		        .replace(/(\d)(?=(\d{3})+\.)/g, function($0, $1) {
		            return $1 + ",";
		        });
		}
		console.log(commafy(1234567.90)); //1,234,567.90
