### ISSUE TITLE
“请解释一下CSS3的Flexbox（弹性盒布局模型）,以及适用场景”的回答

### ISSUE THREAD

**Issue by MKFMIKU** [markyun/My-blog#62]
Flexbox意为"弹性布局"，用来为盒状模型提供最大的灵活性。
采用Flex布局的元素，称为Flex容器（flex container），简称"容器"。它的所有子元素自动成为容器成员，称为Flex项目（flex item），简称"项目"。常规布局是基于块和内联流方向，而Flex布局是基于flex-flow流
可以很方便的用来做局中，能对不同屏幕大小自适应。在布局上有了比以前更加灵活的空间

**Comment by markyun** [comment]
thanks a lot
