### ISSUE TITLE
javaScript思想

### ISSUE THREAD

**Issue by fanboke** [markyun/My-blog#64]
怎么才能快速掌握JavaScript写代码思想呢？有条件了但是感觉，有条件但是不知道怎么写，求大神帮助。。。。

**Comment by fanboke** [comment]
大神给点建议

**Comment by RoberterSP** [comment]
多写些项目就ok了

**Comment by markyun** [comment]
《javascript高级程序设计》（ 高程3）
    《javascript权威指南》（ 犀牛书）
    《编写可维护的JavaScript》
    《JavaScript语言精粹》

先多看几遍把基础打好，然后多写轮子练手，多去知乎回答javascript相关问题~
