### ISSUE TITLE
["1", "2", "3"].map(parseInt)的解释

### ISSUE THREAD

**Issue by deepred5** [markyun/My-blog#66]
返回```[1, NaN, NaN]```的解释中，第三个值是```NaN```并不是因为radix不合法，而是因为```parseInt('3', 2)```转换时，二进制没有3，所以以二进制转换失败，返回```NaN```

**Comment by markyun** [comment]
thanks a lot ！测试并查询了相关文章已经修正。

http://blog.csdn.net/justjavac/article/details/19473199
