### ISSUE TITLE
.background-color:#00deff\9; /*IE6、7、8识别*/

### ISSUE THREAD

**Issue by anlexiaozhan** [markyun/My-blog#69]
.background-color:#00deff\9; /*IE6、7、8识别*/
【background-color 之前没有 . 】
css hack 下面的版本一般用得更多
.test {
	color: #090\9; /* For IE8+ */
	*color: #f00;  /* For IE7 and earlier */
	_color: #ff0;  /* For IE6 and earlier */
}

**Comment by markyun** [comment]
谢谢，【background-color 之前没有 . 】的确写错了，

【		          
        background-color:red;/*所有识别*/
	background-color:#00deff\9; /*IE6、7、8识别*/
	 +background-color:#a200ff;/*IE6、7识别*/
	 _background-color:#1e0bd1;/*IE6识别*/
】也是可以用的。
