### ISSUE TITLE
css定义的权重，这一部分验证了下，请教

### ISSUE THREAD

**Issue by liuchungui** [markyun/My-blog#76]
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        #testId {
            background-color: grey;
        }
        .class1.class2.class3.class4.class5.class6.class7.class8.class9.class10.class11 {
            background-color: red;
        }

    </style>
</head>
<body>
<p id="testId" class="class1 class2 class3 class4 class5 class6 class7 class8 class9 class10 class11">
    测试
</p>
</body>
</html>
```

上面代码背景色仍然是灰色，所以id权重为100，class权重为10，是不正确的吧？

**Comment by ponyoloveyou** [comment]
这跟权重没关系吧  可能你的class部分写错了 你要写的难道不是.class1，.class2，.class3，.class4，.class5，.class6，.class7，.class8，.class9，.class10，.class11 { background-color: red; }？
而且如果你的testId 和其中一个class 作用于同一个元素，下面的代码会覆盖上面的代码   关键我不知道你是不是class  那一部分有没有写错
----- 原始邮件 -----
发件人：liuchungui <notifications@github.com>
收件人：markyun/My-blog <My-blog@noreply.github.com>
主题：[markyun/My-blog]_css定义的权重，这一部分验证了下，请教_(#76)
日期：2016年11月28日 10点59分

`


    
    <title>Title</title>
    <style>
        #testId {
            background-color: grey;
        }
        .class1.class2.class3.class4.class5.class6.class7.class8.class9.class10.class11 {
            background-color: red;
        }
</style>




    测试


`
上面代码背景色仍然是灰色，所以id权重为100，class权重为10，是不正确的吧？

&mdash;

**Comment by w3cay** [comment]
选择器权重计算没有10进制这一说，所以三个臭皮匠也赛不过诸葛亮，即使是11个。
参考《Css.Mastery.Advanced.Web.Standards.Solutions.(2nd.Edition)》
> Unfortunately, specificity is not calculated in base 10 but a high, unspecified, base number. This is to ensure that a highly specific selector, such as an ID selector, is never overridden by lots of less specific selectors, such as type selectors. However, if you have fewer than 10 selectors in a specific selector, you can calculate specificity in base 10 for simplicity’s sake.

**Comment by liuchungui** [comment]
@w3cay 谢谢，受教了
