### ISSUE TITLE
关于css问题的请教

### ISSUE THREAD

**Issue by cute1baby** [markyun/My-blog#78]
之前遇到一个css问题在很多地方都会遇到，是盒模型的折叠引起的。比如说在这种情况下会产生折叠：父级高度不确定，然后给子级设置一个margin值或者padding值，这个时候会产生塌陷效果，无论设置的margin值多大都达不到预期，我不是很明白这种效果产生的原因，所以请教一下。

**Comment by cute1baby** [comment]
@weakish @FounderIsShadowWalker

**Comment by FounderIsShadowWalker** [comment]
你是说给子元素设置margin，然后传递到父标签吗？

**Comment by markyun** [comment]
给出你的代码片段再问大家、

**Comment by LeoEatle** [comment]
了解一下什么叫BFC
