### ISSUE TITLE
垂直居中问题

### ISSUE THREAD

**Issue by IvyLian** [markyun/My-blog#79]
垂直居中的解决办法中，当div 相对定位的时候，只实现左右居中，并且高度只显示了一半。
利用 flex 布局 这个解决方法也没用实现垂直居中，只实现了左右。
在mac chrome 版本 55.0.2883.75 (64-bit)上测试的。

**Comment by Angelyu89** [comment]
垂直居中方法：
   vertical-align: middle;
   display: table-cell;

**Comment by IvyLian** [comment]
@Angelyu89  估计我没表述清楚，我意思是code 里边关于前端面试题，" div 垂直居中" 提供的几种方法，代码里标注说“当div 为display:relative时，也可以实现垂直居中”，但是我测试下来，只有absolute时，才有效。测试的浏览器  chrome 和 firefox。
