### ISSUE TITLE
我想下载这个文档到电脑上，怎么弄？？每天打开网页版看眼睛好疼，想打印成纸质档来看

### ISSUE THREAD

**Issue by zerocup** [markyun/My-blog#84]
我想下载这个文档到电脑上，怎么弄？？每天打开网页版看眼睛好疼，想打印成纸质档来看

**Comment by dxcqcv** [comment]
可以在火狐浏览器上装stylish改变网页颜色

**Comment by ma450921** [comment]
你是想打印markdown文件吗？clone这个项目到本地，解压后把.md的文件拖入chrome浏览器，然后右键打印，进入打印界面选择保存成pdf就可以了，或者你可以下载一个markdown阅读器，也可以转为pdf的。

**Comment by markyun** [comment]
@zerocup  如@ma450921  所说，你把markdown下载到自己电脑上用markdown软件打开可以打印或者导出成pdf打印。
