### ISSUE TITLE
如何判断当前脚本运行在浏览器还是node环境中？（阿里）

### ISSUE THREAD

**Issue by hanzhangyu** [markyun/My-blog#95]
window会报错吧，我觉得应该是这个吧
```javascript
var result;
try{
this===window&&result='window'
}catch(){
result='node'
}
```

**Comment by Zjingwen** [comment]
(function(){
	if(this.window) console.log( 'window' ); return false;
	console.log('node');
})(this)

**Comment by hanzhangyu** [comment]
@Zjingwen 谢谢指正原来`this.window===window`啊，是我孤陋寡闻了，哈哈。

**Comment by xiaomizhou66** [comment]
[通过判断Global对象是否为window，如果不为window，当前脚本没有运行在浏览器中]
 方便自己用的，占位置放几个字~~~☺

**Comment by xuzihao0226** [comment]
this === window ? 'window':'browser'

**Comment by xuzihao0226** [comment]
this === window? 'window':'node'
